name: Question
description: 提出使用或开发相关问题
title: "[Question]: "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: 问题
      description: 请尽可能提供上下文、代码或日志。
    validations:
      required: true
